### ISSUE TITLE
Dataset Preparation

### ISSUE THREAD

**Issue by AyeshaSarwar** [xssstory/STAS#2]
It is mentioned in the data preprocess step that every article/summary is splitted by the <S_SEP> token. 
You meant like this:

<S_SEP>sentence 1<S_SEP>sentence 2<S_SEP>

It would have been better if you have provided with the example data.

**Comment by xssstory** [comment]
Thanks for your suggestion, we provide an example in README now.  :)

**Comment by AyeshaSarwar** [comment]
Thank you :)) I am grateful to you..

**Comment by AyeshaSarwar** [comment]
It is mentioned in the readme.txt file that we should get only 6 files. We have 92k files for CCN dataset. Are we suppose to merge them? I have separated the summaries.
How should we split the data into the mentioned 6 files i.e train.article, train.summary, valid.article, valid.summary, test.article and test.summary?
