### ISSUE TITLE
Dataset Preparation for STAS

### ISSUE THREAD

**Issue by AyeshaSarwar** [xssstory/STAS#3]
It is mentioned in the readme.txt file that we should get only 6 files i.e train.article, train.summary, valid.article, valid.summary, test.article and test.summary. But, we have 92k files for CCN dataset. I have separated the summaries for all these files.

How should we split the data into the mentioned 6 files i.e train.article, train.summary, valid.article, valid.summary, test.article and test.summary? Are we suppose to merge them? If yes, how? What will be the format or the criteria?

Thanks in advance.

**Comment by AyeshaSarwar** [comment]
Hi. I managed to transform the files into mentioned 6 files.

I want to ask if the STAS model has a limitation of 512 tokens as we do have for BERT?

**Comment by xssstory** [comment]
Yes,  limited by the positional embedding of RoBERTa, all documents are truncated to 512 subword tokens

**Comment by AyeshaSarwar** [comment]
How can we work with longer documents? Is this possible to increase the length of the document?

**Comment by xssstory** [comment]
Maybe You can try to initialize new positional embeddings :)

**Comment by AyeshaSarwar** [comment]
Can you please help me with this error?
I have uploaded 6 files in the data/cnndm/directory; test.article and test.summary in the test folder; valid.article and valid.summary in the validation folder. I do not have enough resources to run this code multiple times. I have excluded the documents that have summary not longer than 50 words and I had to look for empty documents as well. Your help will be much appreciated.  
I didn't understand this logic of assertion error. Is there anything wrong with the input? Because code is the same. I am currently trying for CNN dataset. I changed the name of folder "validation" in your command to "valid" but it is still throwing me the error.

or can u please upload the scripts you have used to clean the data because this is most probably because of the issue in the data; or may be you can upload your cleaned data (if possible)?

![34](https://user-images.githubusercontent.com/51691311/115900820-d1a23a00-a479-11eb-8168-507e44de505e.PNG)

![56](https://user-images.githubusercontent.com/51691311/115900279-327d4280-a479-11eb-9210-dd27a68ad34b.PNG)

**Comment by AyeshaSarwar** [comment]
How is that calculating the pred_scores greater than the number of sentences in the article?

![Capture-2](https://user-images.githubusercontent.com/51691311/116165904-4396af80-a716-11eb-96b3-17d5cc0723b0.PNG)

**Comment by AyeshaSarwar** [comment]
> Maybe You can try to initialize new positional embeddings :)

Will it resolve the issue?
Doesnt RoBERTa concatenates after truncating?
@XingxingZhang @xssstory 
Do I just need to change the tokenizer?

**Comment by AyeshaSarwar** [comment]
I am trying to increase the summary length from topk=3 but it is still producing a summary with 3 sentences?
@XingxingZhang @xssstory

**Comment by AyeshaSarwar** [comment]
Kindly help me in this regard as I have a very strict deadline to deliver a project and I am way too badly stuck at this. I can only ask you guys for your help.
Thanks
Help much appreciated.

**Comment by xssstory** [comment]
> Can you please help me with this error?
> I have uploaded 6 files in the data/cnndm/directory; test.article and test.summary in the test folder; valid.article and valid.summary in the validation folder. I do not have enough resources to run this code multiple times. I have excluded the documents that have summary not longer than 50 words and I had to look for empty documents as well. Your help will be much appreciated.
> I didn't understand this logic of assertion error. Is there anything wrong with the input? Because code is the same. I am currently trying for CNN dataset. I changed the name of folder "validation" in your command to "valid" but it is still throwing me the error.
> 
> or can u please upload the scripts you have used to clean the data because this is most probably because of the issue in the data; or maybe you can upload your cleaned data (if possible)?
> 
> ![34](https://user-images.githubusercontent.com/51691311/115900820-d1a23a00-a479-11eb-8168-507e44de505e.PNG)
> 
> ![56](https://user-images.githubusercontent.com/51691311/115900279-327d4280-a479-11eb-9210-dd27a68ad34b.PNG)

It seems that you generate more pred_scores  than the number of sentences in the article. I don't know the details, you can also step into fairseq/models/extract_sum_recovery_transformer_pagerank.py to monitor the scoring process.

> I am trying to increase the summary length from topk=3 but it is still producing a summary with 3 sentences?
> @XingxingZhang @xssstory

Which script did you use to generate a summary?

**Comment by AyeshaSarwar** [comment]
> > Can you please help me with this error?
> > I have uploaded 6 files in the data/cnndm/directory; test.article and test.summary in the test folder; valid.article and valid.summary in the validation folder. I do not have enough resources to run this code multiple times. I have excluded the documents that have summary not longer than 50 words and I had to look for empty documents as well. Your help will be much appreciated.
> > I didn't understand this logic of assertion error. Is there anything wrong with the input? Because code is the same. I am currently trying for CNN dataset. I changed the name of folder "validation" in your command to "valid" but it is still throwing me the error.
> > or can u please upload the scripts you have used to clean the data because this is most probably because of the issue in the data; or maybe you can upload your cleaned data (if possible)?
> > ![34](https://user-images.githubusercontent.com/51691311/115900820-d1a23a00-a479-11eb-8168-507e44de505e.PNG)
> > ![56](https://user-images.githubusercontent.com/51691311/115900279-327d4280-a479-11eb-9210-dd27a68ad34b.PNG)
> 
> It seems that you generate more pred_scores than the number of sentences in the article. I don't know the details, you can also step into fairseq/models/extract_sum_recovery_transformer_pagerank.py to monitor the scoring process.
> 
> > I am trying to increase the summary length from topk=3 but it is still producing a summary with 3 sentences?
> > @XingxingZhang @xssstory
> 
> Which script did you use to generate a summary?

I was able to resolve the first error.

After I execute ensemble.py, and evaluate_ensemble.py files, I get the summary in released_model/ensemble_result/ensemble/test and valid folders.

Isnt the topk variable in your code handling the number of sentences to be included in the final summary?

**Comment by xssstory** [comment]
> > > Can you please help me with this error?
> > > I have uploaded 6 files in the data/cnndm/directory; test.article and test.summary in the test folder; valid.article and valid.summary in the validation folder. I do not have enough resources to run this code multiple times. I have excluded the documents that have summary not longer than 50 words and I had to look for empty documents as well. Your help will be much appreciated.
> > > I didn't understand this logic of assertion error. Is there anything wrong with the input? Because code is the same. I am currently trying for CNN dataset. I changed the name of folder "validation" in your command to "valid" but it is still throwing me the error.
> > > or can u please upload the scripts you have used to clean the data because this is most probably because of the issue in the data; or maybe you can upload your cleaned data (if possible)?
> > > ![34](https://user-images.githubusercontent.com/51691311/115900820-d1a23a00-a479-11eb-8168-507e44de505e.PNG)
> > > ![56](https://user-images.githubusercontent.com/51691311/115900279-327d4280-a479-11eb-9210-dd27a68ad34b.PNG)
> > 
> > 
> > It seems that you generate more pred_scores than the number of sentences in the article. I don't know the details, you can also step into fairseq/models/extract_sum_recovery_transformer_pagerank.py to monitor the scoring process.
> > > I am trying to increase the summary length from topk=3 but it is still producing a summary with 3 sentences?
> > > @XingxingZhang @xssstory
> > 
> > 
> > Which script did you use to generate a summary?
> 
> I was able to resolve the first error.
> 
> After I execute ensemble.py, and evaluate_ensemble.py files, I get the summary in released_model/ensemble_result/ensemble/test and valid folders.
> 
> Isnt the topk variable in your code handling the number of sentences to be included in the final summary?

If you want to change the topk, you can modify the code of ensemble.py in line 78 and line 107.  ``if len(pred_idx) >= 3:''

**Comment by AyeshaSarwar** [comment]
> > > > Can you please help me with this error?
> > > > I have uploaded 6 files in the data/cnndm/directory; test.article and test.summary in the test folder; valid.article and valid.summary in the validation folder. I do not have enough resources to run this code multiple times. I have excluded the documents that have summary not longer than 50 words and I had to look for empty documents as well. Your help will be much appreciated.
> > > > I didn't understand this logic of assertion error. Is there anything wrong with the input? Because code is the same. I am currently trying for CNN dataset. I changed the name of folder "validation" in your command to "valid" but it is still throwing me the error.
> > > > or can u please upload the scripts you have used to clean the data because this is most probably because of the issue in the data; or maybe you can upload your cleaned data (if possible)?
> > > > ![34](https://user-images.githubusercontent.com/51691311/115900820-d1a23a00-a479-11eb-8168-507e44de505e.PNG)
> > > > ![56](https://user-images.githubusercontent.com/51691311/115900279-327d4280-a479-11eb-9210-dd27a68ad34b.PNG)
> > > 
> > > 
> > > It seems that you generate more pred_scores than the number of sentences in the article. I don't know the details, you can also step into fairseq/models/extract_sum_recovery_transformer_pagerank.py to monitor the scoring process.
> > > > I am trying to increase the summary length from topk=3 but it is still producing a summary with 3 sentences?
> > > > @XingxingZhang @xssstory
> > > 
> > > 
> > > Which script did you use to generate a summary?
> > 
> > 
> > I was able to resolve the first error.
> > After I execute ensemble.py, and evaluate_ensemble.py files, I get the summary in released_model/ensemble_result/ensemble/test and valid folders.
> > Isnt the topk variable in your code handling the number of sentences to be included in the final summary?
> 
> If you want to change the topk, you can modify the code of ensemble.py in line 78 and line 107. ``if len(pred_idx) >= 3:''

@xssstory 

Ok, I will check this. Thank You.
Will the 512 token limit with Roberta base be resolved if I only change the tokenizer? It will then consider the whole document according to the new tokenizer? Or I have to make other changes as well?

**Comment by AyeshaSarwar** [comment]
@XingxingZhang @xssstory 

Will the 512 token limit with Roberta base in this model be resolved if I only change the tokenizer? It will then consider the whole document according to the new tokenizer? Or I have to make other changes as well?

Looking forward for your kind reply.

Much thanks in advance.

**Comment by AyeshaSarwar** [comment]
> @xssstory
> 
> Will the 512 token limit with Roberta base in this model be resolved if I only change the tokenizer? It will then consider the whole document according to the new tokenizer? Or I have to make other changes as well?
> 
> looking forward for your kind reply.
> 
> Much thanks in advance.

@xssstory 
I have a dataset with long documents. I want to ask if just changing the tokenizer will likely resolve the issue or anyother thing that you can suggest. I would highly appreciate your kind help.

Thanks

**Comment by xssstory** [comment]
> > @xssstory
> > Will the 512 token limit with Roberta base in this model be resolved if I only change the tokenizer? It will then consider the whole document according to the new tokenizer? Or I have to make other changes as well?
> > looking forward for your kind reply.
> > Much thanks in advance.
> 
> @xssstory
> I have a dataset with long documents. I want to ask if just changing the tokenizer will likely resolve the issue or anyother thing that you can suggest. I would highly appreciate your kind help.
> 
> Thanks

The limit is that the pre-trained Roberta model has the maximum positional embedding of 512. If you want to handle a longer sequence, you should consider how to handle the positional embedding larger than 512. Another thing is that a longer sequence needs more computing resources.

**Comment by AyeshaSarwar** [comment]
> > > @xssstory
> > > Will the 512 token limit with Roberta base in this model be resolved if I only change the tokenizer? It will then consider the whole document according to the new tokenizer? Or I have to make other changes as well?
> > > looking forward for your kind reply.
> > > Much thanks in advance.
> > 
> > 
> > @xssstory
> > I have a dataset with long documents. I want to ask if just changing the tokenizer will likely resolve the issue or anyother thing that you can suggest. I would highly appreciate your kind help.
> > Thanks
> 
> The limit is that the pre-trained Roberta model has the maximum positional embedding of 512. If you want to handle a longer sequence, you should consider how to handle the positional embedding larger than 512. Another thing is that a longer sequence needs more computing resources.

@xssstory 

Sorry for the trouble :((

So, I need to replace the value for the roberta_model variable i.e. allenai/longformer-base-4096? Will it work using longformers  instead of roberta base model?

**Comment by xssstory** [comment]
> > > > @xssstory
> > > > Will the 512 token limit with Roberta base in this model be resolved if I only change the tokenizer? It will then consider the whole document according to the new tokenizer? Or I have to make other changes as well?
> > > > looking forward for your kind reply.
> > > > Much thanks in advance.
> > > 
> > > 
> > > @xssstory
> > > I have a dataset with long documents. I want to ask if just changing the tokenizer will likely resolve the issue or anyother thing that you can suggest. I would highly appreciate your kind help.
> > > Thanks
> > 
> > 
> > The limit is that the pre-trained Roberta model has the maximum positional embedding of 512. If you want to handle a longer sequence, you should consider how to handle the positional embedding larger than 512. Another thing is that a longer sequence needs more computing resources.
> 
> @xssstory
> 
> Sorry for the trouble :((
> 
> So, I need to replace the value for the roberta_model variable i.e. allenai/longformer-base-4096? Will it work using longformers instead of roberta base model?

I think you can have a try :)
