### ISSUE TITLE
Order of files in ensemble results and discrepancy in len of lines.

### ISSUE THREAD

**Issue by Wonder1905** [xssstory/STAS#4]
Hi, thanks for the great work.
I'm wondering about the ensemble results, there are
[ Pacsum results ](https://github.com/xssstory/STAS/blob/master/released_model/cnndm_model/ensemble_result/pacsum/61.test.txt
)And [your  results (Stas)](https://github.com/xssstory/STAS/blob/master/released_model/cnndm_model/ensemble_result/stas/13.test.txt), Now each F or T represent a sentence in some file, why does Pacsum number of lines are larger then Stas? For example , for the first file Pacsum results are:
`Predicted Labels:	T T F F T F F F F F F F F F F F F F F F F F F F F F F F F F`
Stas results are:
`Predicted Labels:	T T F T F F F F F F F F F F F F F`.

One more question , do we have a way to catch which file each line represents? is there any order you used?

Thanks a lot!

**Comment by xssstory** [comment]
In STAS, limited by the positional embedding of RoBERTa, all documents are truncated to 512 subword tokens. That is why the number of lines is smaller.

For the second question, we provide the output summary of PACSUM, please refer to https://github.com/xssstory/STAS/tree/master/released_model/cnndm_model/ensemble_result/ensemble for the results.

**Comment by Wonder1905** [comment]
Great , thanks a lot !!!
Closing issue.
