### ISSUE TITLE
There is an issue with setup.py.

### ISSUE THREAD

**Issue by xcc-1921** [xssstory/STAS#5]
When I tried to run setup.py directly using cmd, I encountered the error message "UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 969: illegal multibyte sequence".

To fix this, I should change "with open('README.md') as f:" to "with open('README.md', encoding='utf-8') as f:"  in line 16.

**Comment by xssstory** [comment]
Thanks for your feedback.
It depends on the default encoding method of your platform.
I have updated the code.
