### ISSUE TITLE
Questions about Training Program and Input Data.

### ISSUE THREAD

**Issue by xcc-1921** [xssstory/STAS#7]
Hello, I have entered the preparation stage for training. The program should be running normally now. Thank you very much for your assistance.

Currently, I am preparing to train other languages and have found a dictionary on my own.

 However, I have not been able to successfully find the input for the dictionary of your software, especially I am not sure where the tokens are input from.
 The file ‘roberta-base-vocab.json’ does not specify the input for the vectors, so I think it cannot be modified independently.

Also, I will have multiple articles to train, and I would like to ask if the program can read texts according to the folder. It seems to be possible in the code, but I want to confirm if I have misunderstood.

I am planning to train my data based on the pre-trained model you provided, but my texts currently do not have summaries. Can I still train them?

(Thank you again for your help.)

**Comment by xssstory** [comment]
Don't modify the file "roberta-base-vocab.json". Our method is based on the pre-trained model RoBERTa, the file "roberta-base-vocab.json" also comes RoBERTa.
Please refer to "get-data-bpe.sh" to generate the dataset, "roberta-base-vocab.json" is used here.
Our method focuses on unsupervised training, you can have a try even if you don't have summaries.

**Comment by xcc-1921** [comment]
> Don't modify the file "roberta-base-vocab.json". Our method is based on the pre-trained model RoBERTa, the file "roberta-base-vocab.json" also comes RoBERTa. Please refer to "get-data-bpe.sh" to generate the dataset, "roberta-base-vocab.json" is used here. Our method focuses on unsupervised training, you can have a try even if you don't have summaries.

Thank you. You are absolutely right. 

Additionally, your 'fairseq/tokenizer.py' is missing some imports. If I'm not mistaken, you should add the following at the beginning of that file:

import torch
from collections import Counter
